on:
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 23.3.1
          elixir-version: 1.11.4

      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix test

    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_PASSWORD: "postgres"
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
